CREATE TABLE `biz_product` (
  `id` varchar(36) NOT NULL COMMENT '主键ID',
  `product_name` varchar(200) NOT NULL COMMENT '产品名称',
  `spu_name` varchar(255) NOT NULL COMMENT '收费项目名称',
  `category_id` varchar(255) DEFAULT NULL COMMENT '外部类目ID',
  `category_name` varchar(255) DEFAULT NULL COMMENT '外部类目名',
  `data_language` varchar(50) DEFAULT NULL COMMENT '当前语言',
  `cost_include_traveller_info` json DEFAULT NULL COMMENT '费用包含的出行人数量',
  `reservation_type` varchar(50) DEFAULT NULL COMMENT '预约类型',
  `ticket_kind_name` varchar(255) NOT NULL COMMENT '票种名称',
  `ticket_kind_id` varchar(255) DEFAULT NULL COMMENT '票种ID',
  `session_name` varchar(255) DEFAULT NULL COMMENT '场次名称',
  `region_name` varchar(255) DEFAULT NULL COMMENT '区域名称',
  `real_name` varchar(50) DEFAULT NULL COMMENT '是否实名制',
  `ticket_category` varchar(50) NOT NULL COMMENT '门票分类',
  `ticket_type` varchar(50) NOT NULL COMMENT '出票类型',
  `stock_type` varchar(50) DEFAULT NULL COMMENT '库存类型',
  `instant_confirm` varchar(50) DEFAULT NULL COMMENT '是否立即确认',
  `instant_confirm_minute` int DEFAULT NULL COMMENT '二次确认时长(分钟)',
  `voucher_minute_type` varchar(50) DEFAULT NULL COMMENT '发送凭证时间类型',
  `instant_confirm_type` varchar(50) DEFAULT NULL COMMENT '二次确认时长类型',
  `voucher_minute` int DEFAULT NULL COMMENT '发送凭证时间(分钟)',
  `confirm_description` text DEFAULT NULL COMMENT '确认方式描述',
  `note` text DEFAULT NULL COMMENT '注意事项',
  `special_info` text DEFAULT NULL COMMENT '特殊信息',
  `description` text DEFAULT NULL COMMENT '描述',
  `transport` text DEFAULT NULL COMMENT '交通信息',
  `pick_up_description` text DEFAULT NULL COMMENT '接送详情',
  `cost_include` text NOT NULL COMMENT '费用包含',
  `cost_not_include` text DEFAULT NULL COMMENT '费用不包含',
  `time_zone` int DEFAULT NULL COMMENT '时区',
  `is_session_ticket` varchar(50) NOT NULL COMMENT '是否场次票',
  `is_zero_ticket` varchar(50) DEFAULT NULL COMMENT '是否零元票',
  `is_interval_ticket` varchar(50) DEFAULT NULL COMMENT '是否区间票',
  `is_area_ticket` varchar(50) NOT NULL COMMENT '是否区域票',
  `invoice_description` text DEFAULT NULL COMMENT '发票说明',
  `insurance_description` text DEFAULT NULL COMMENT '保险说明',
  `application_condition` text DEFAULT NULL COMMENT '使用条件',
  `currency` varchar(50) DEFAULT NULL COMMENT '币种',
  `ext_info` text DEFAULT NULL COMMENT '扩展信息',
  `sale_start_date` varchar(10) DEFAULT NULL COMMENT '销售开始日期 格式：yyyy-MM-dd',
  `sale_start_time` varchar(8) DEFAULT NULL COMMENT '销售开始时间 格式：HH:mm:ss',
  `sale_end_date` varchar(10) DEFAULT NULL COMMENT '销售结束日期 格式：yyyy-MM-dd',
  `sale_end_time` varchar(8) DEFAULT NULL COMMENT '销售结束时间 格式：HH:mm:ss',
  `sale_week_day` json DEFAULT NULL COMMENT '星期几可售',
  `settlement_type` varchar(50) DEFAULT NULL COMMENT '结算方式',
  `online_start_date` varchar(19) DEFAULT NULL COMMENT '上架开始时间 格式：yyyy-MM-dd HH:mm:ss',
  `online_end_date` varchar(19) DEFAULT NULL COMMENT '上架结束时间 格式：yyyy-MM-dd HH:mm:ss',
  `product_url` json DEFAULT NULL COMMENT '产品URL列表',
  `wheelchair_access` varchar(50) DEFAULT NULL COMMENT '是否有轮椅通道',
  `skip_line` varchar(50) DEFAULT NULL COMMENT '是否包含免排队',
  `highlights` text DEFAULT NULL COMMENT '亮点介绍',
  `interval_name` varchar(255) DEFAULT NULL COMMENT '区间名称',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_product_name` (`product_name`),
  KEY `idx_spu_name` (`spu_name`),
  KEY `idx_ticket_kind_name` (`ticket_kind_name`),
  KEY `idx_category_id` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品信息表';